version: '3.8'

services:
  # PostgreSQL（権限問題を修正）
  postgres:
    image: postgres:15-alpine
    container_name: recruitment_db
    environment:
      POSTGRES_DB: recruitment_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres123
      PGDATA: /var/lib/postgresql/data/pgdata  # 権限問題を回避
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
      - ./database/secure-schema.sql:/docker-entrypoint-initdb.d/02-secure-schema.sql
      - ./database/init-data.sql:/docker-entrypoint-initdb.d/03-init-data.sql
    ports:
      - "5432:5432"
    networks:
      - app_network

  # Node.jsアプリケーション（バックエンド）
  app:
    image: node:18-alpine
    container_name: recruitment_app
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: recruitment_system
      DB_USER: postgres
      DB_PASSWORD: postgres123
      JWT_SECRET: dev_jwt_secret_change_in_production
      PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - postgres
    command: sh -c "npm install && npm run dev"

  # pgAdmin（データベース管理ツール）
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: recruitment_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@company.local
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
    ports:
      - "5050:80"
    networks:
      - app_network
    depends_on:
      - postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  pgadmin_data:
    driver: local